### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MJRLegends** [D-prog-55/ConcreteMod#7]
Hello,

Please could you add a config option to disable "Colored Concrete (from Minecraft 1.12 snapshot 17w06a, often refered to as "vanilla")" feature as i really wanna use this mod for the other features but i cant use it due to i have chisel mod and it also adds Colored Concrete, and using them together is causing issues...

Would be amazing if you could add this feature

MJRLegends

**Comment by MJRLegends** [comment]
Also i know you have the Chisel compatibility but i'd rather have one set of Colored Concrete not two that have the same texture but can be switched between each other to give same textured blocks but one has chisel compatibility ... seems weird to me

**Comment by D-prog-55** [comment]
ok

**Comment by MJRLegends** [comment]
@D-prog-55 I hope that ok, means yes i will add it haha also amazing textures on your blocks in your mod :D i like them a lot

**Comment by D-prog-55** [comment]
thanks. But right now I'm working on something different. If you're interested:
https://github.com/D-prog-55/Clickbait-Sim
