### ISSUE TITLE
[1.7.10] Block override

### ISSUE THREAD

**Issue by ensirius** [D-prog-55/ConcreteMod#9]
It's possible using mod sand replace blocks: 

http://prntscr.com/gf1ab7
https://prnt.sc/gf1afj

**Comment by D-prog-55** [comment]
I don't understand what you did. Can you post everything you did between the two screenshots?

**Comment by ensirius** [comment]
Here steps to repdrouce bug:
1. prepare https://i.imgur.com/DcK8Epf.jpg
2. place block https://i.imgur.com/YYWJgxd.jpg
3. block replaces east badrock https://i.imgur.com/ICTUZCQ.jpg

**Comment by D-prog-55** [comment]
That's weird. I don't know why it acts like this. I will try to fix it asap.

**Comment by ensirius** [comment]
It's works only if X coordinate is negative

**Comment by D-prog-55** [comment]
Must be a vanilla bug. Will check EntityFallingSand.

**Comment by ensirius** [comment]
I think you messed up with numeric convertations

**Comment by D-prog-55** [comment]
I copy-pasted the code I made for 1.10 and it worked, so that's probably an inconsistency between versions.

**Comment by ensirius** [comment]
I made a fix

**Comment by D-prog-55** [comment]
Saw it. But since I will update 1.2 (maybe 1.3) to 1.7.10 soon (which doesn't have the class you fixed anymore), so I won't merge it (but I will do what you did to the code as it's sorta the same).
